window.DATA = {};
window.DATA.runners = [
    {
        id: 1,
        car: 1,
        name: "Katka",
        time_on_10km: 65
    }, {
        id: 2,
        car: 1,
        name: "Jitka",
        time_on_10km: 60
    }, {
        id: 3,
        car: 2,
        name: "Mato",
        time_on_10km: 50
    }, {
        id: 4,
        car: 2,
        name: "Vlado",
        time_on_10km: 46
    }, {
        id: 5,
        car: 2,
        name: "Peto",
        time_on_10km: 60
    }, {
        id: 6,
        car: 2,
        name: "Marcel",
        time_on_10km: 50
    }, {
        id: 7,
        car: 3,
        name: "Palo T.",
        time_on_10km: 48
    }, {
        id: 8,
        car: 3,
        name: "Palo B.",
        time_on_10km: 48
    }, {
        id: 9,
        car: 3,
        name: "Tibor",
        time_on_10km: 52
    }, {
        id: 10,
        car: 3,
        name: "Marek",
        time_on_10km: 52
    }, {
        id: 11,
        car: 1,
        name: "Patrik",
        time_on_10km: 55
    }, {
        id: 12,
        car: 1,
        name: "Darina",
        time_on_10km: 54
    }
];

window.DATA.sections_static = [
    {
        id: 1,
        length: 9.8,
        elevation_up: 100,
        elevation_down: 450,
        k: 0.91334,
        from: "Demänovská dolina"
    }, {
        id: 2,
        length: 10.4,
        elevation_up: 120,
        elevation_down: 230,
        k: 0.9846,
        from: "Pavčina lehota"
    }, {
        id: 3,
        length: 11.9,
        elevation_up: 320,
        elevation_down: 250,
        k: 1.058,
        from: "Ľubeľa"
    }, {
        id: 4,
        length: 9.5,
        elevation_up: 530,
        elevation_down: 90,
        k: 1.1684,
        from: "Ľupčianska dolina"
    }, {
        id: 5,
        length: 11,
        elevation_up: 30,
        elevation_down: 530,
        k: 0.90455,
        from: "Železnô"
    }, {
        id: 6,
        length: 9.8,
        elevation_up: 230,
        elevation_down: 110,
        k: 1.0398,
        from: "Liptovská Osada"
    }, {
        id: 7,
        length: 9.4,
        elevation_up: 500,
        elevation_down: 550,
        k: 1.084,
        from: "Vyšná Revúca"
    }, {
        id: 8,
        length: 9.5,
        elevation_up: 430,
        elevation_down: 500,
        k: 1.16623,
        from: "Hotel Šturec"
    }, {
        id: 9,
        length: 7.8,
        elevation_up: 120,
        elevation_down: 250,
        k: 0.936,
        from: "Baláže"
    }, {
        id: 10,
        length: 9.6,
        elevation_up: 70,
        elevation_down: 150,
        k: 1.01663,
        from: "Selce"
    }, {
        id: 11,
        length: 9.6,
        elevation_up: 80,
        elevation_down: 100,
        k: 0.98542,
        from: "Banská Bystrica"
    }, {
        id: 12,
        length: 8,
        elevation_up: 100,
        elevation_down: 100,
        k: 0.9963,
        from: "Sielnica"
    }, {
        id: 13,
        length: 11,
        elevation_up: 100,
        elevation_down: 140,
        k: 1,
        from: "Stráže"
    }, {
        id: 14,
        length: 11.6,
        elevation_up: 150,
        elevation_down: 150,
        k: 1.056,
        from: "Hronská Dúbrava"
    }, {
        id: 15,
        length: 10,
        elevation_up: 70,
        elevation_down: 100,
        k: 0.989,
        from: "Žiar nad Hronom"
    }, {
        id: 16,
        length: 8.4,
        elevation_up: 120,
        elevation_down: 130,
        k: 0.94643,
        from: "Hliník nad Hronom"
    }, {
        id: 17,
        length: 7,
        elevation_up: 140,
        elevation_down: 150,
        k: 1.0443,
        from: "Žarnovica"
    }, {
        id: 18,
        length: 8.6,
        elevation_up: 100,
        elevation_down: 120,
        k: 0.9535,
        from: "Voznica"
    }, {
        id: 19,
        length: 11,
        elevation_up: 130,
        elevation_down: 180,
        k: 1.03826,
        from: "Brehy"
    }, {
        id: 20,
        length: 11.7,
        elevation_up: 170,
        elevation_down: 150,
        k: 1.0837,
        from: "Hronský Beňadik"
    }, {
        id: 21,
        length: 7.4,
        elevation_up: 40,
        elevation_down: 60,
        k: 0.9891,
        from: "Nemčiňany"
    }, {
        id: 22,
        length: 8.7,
        elevation_up: 20,
        elevation_down: 50,
        k: 0.9874,
        from: "Nevidzany"
    }, {
        id: 23,
        length: 9.3,
        elevation_up: 20,
        elevation_down: 20,
        k: 1,
        from: "Vráble"
    }, {
        id: 24,
        length: 9.6,
        elevation_up: 70,
        elevation_down: 80,
        k: 1.00733,
        from: "Kmetovo"
    }, {
        id: 25,
        length: 8.7,
        elevation_up: 20,
        elevation_down: 20,
        k: 1.0633,
        from: "Komjatice"
    }, {
        id: 26,
        length: 10.6,
        elevation_up: 10,
        elevation_down: 20,
        k: 1.0151,
        from: "Rastislavice"
    }, {
        id: 27,
        length: 11.2,
        elevation_up: 20,
        elevation_down: 10,
        k: 1.0768,
        from: "Selice"
    }, {
        id: 28,
        length: 11.8,
        elevation_up: 10,
        elevation_down: 20,
        k: 1.0584,
        from: "Šaľa"
    }, {
        id: 29,
        length: 10.7,
        elevation_up: 20,
        elevation_down: 20,
        k: 1.11215,
        from: "Horné Saliby"
    }, {
        id: 30,
        length: 7.4,
        elevation_up: 20,
        elevation_down: 20,
        k: 1.10135,
        from: "Čierna Voda"
    }, {
        id: 31,
        length: 11.4,
        elevation_up: 20,
        elevation_down: 20,
        k: 1.05446,
        from: "Potôňské Lúky"
    }, {
        id: 32,
        length: 7.2,
        elevation_up: 20,
        elevation_down: 20,
        k: 1.0972,
        from: "Veľký Lég"
    }, {
        id: 33,
        length: 7.9,
        elevation_up: 10,
        elevation_down: 10,
        k: 1.08228,
        from: "Čukárska Paka"
    }, {
        id: 34,
        length: 8.4,
        elevation_up: 20,
        elevation_down: 20,
        k: 1.093,
        from: "Čilistov"
    }, {
        id: 35,
        length: 11.3,
        elevation_up: 10,
        elevation_down: 0,
        k: 1.0824,
        from: "Hamuliakovo"
    }, {
        id: 36,
        length: 8.9,
        elevation_up: 50,
        elevation_down: 50,
        k: 1.099,
        from: "Jamaica  (BA hrádza)"
    }
];