window.DATA = {};
window.DATA.runners = [
    {
        "id": 1,
        "car": 1,
        "name": "Katka",
        "time_on_10km": 65
    }, {
        "id": 2,
        "car": 1,
        "name": "Jitka",
        "time_on_10km": 60
    }, {
        "id": 3,
        "car": 2,
        "name": "Mato",
        "time_on_10km": 50
    }, {
        "id": 4,
        "car": 2,
        "name": "Vlado",
        "time_on_10km": 46
    }, {
        "id": 5,
        "car": 2,
        "name": "Peto",
        "time_on_10km": 60
    }, {
        "id": 6,
        "car": 2,
        "name": "Marcel",
        "time_on_10km": 50
    }, {
        "id": 7,
        "car": 3,
        "name": "Palo T.",
        "time_on_10km": 48
    }, {
        "id": 8,
        "car": 3,
        "name": "Palo B.",
        "time_on_10km": 48
    }, {
        "id": 9,
        "car": 3,
        "name": "Tibor",
        "time_on_10km": 52
    }, {
        "id": 10,
        "car": 3,
        "name": "Marek",
        "time_on_10km": 52
    }, {
        "id": 11,
        "car": 1,
        "name": "Patrik",
        "time_on_10km": 55
    }, {
        "id": 12,
        "car": 1,
        "name": "Darina",
        "time_on_10km": 54
    }
];

window.DATA.sections_static = [
    {
        "id": 1,
        "length": 9.8,
        "elevation_up": 100,
        "elevation_down": 450
    }, {
        "id": 2,
        "length": 10.4,
        "elevation_up": 120,
        "elevation_down": 230
    }, {
        "id": 3,
        "length": 11.9,
        "elevation_up": 320,
        "elevation_down": 250
    }, {
        "id": 4,
        "length": 9.5,
        "elevation_up": 530,
        "elevation_down": 90
    }, {
        "id": 5,
        "length": 11,
        "elevation_up": 30,
        "elevation_down": 530
    }, {
        "id": 6,
        "length": 9.8,
        "elevation_up": 230,
        "elevation_down": 110
    }, {
        "id": 7,
        "length": 9.4,
        "elevation_up": 500,
        "elevation_down": 550
    }, {
        "id": 8,
        "length": 9.5,
        "elevation_up": 430,
        "elevation_down": 500
    }, {
        "id": 9,
        "length": 7.8,
        "elevation_up": 120,
        "elevation_down": 250
    }, {
        "id": 10,
        "length": 10.2,
        "elevation_up": 70,
        "elevation_down": 150
    }, {
        "id": 11,
        "length": 9,
        "elevation_up": 80,
        "elevation_down": 100
    }, {
        "id": 12,
        "length": 8,
        "elevation_up": 100,
        "elevation_down": 100
    }, {
        "id": 13,
        "length": 11,
        "elevation_up": 100,
        "elevation_down": 140
    }, {
        "id": 14,
        "length": 11.6,
        "elevation_up": 150,
        "elevation_down": 150
    }, {
        "id": 15,
        "length": 10,
        "elevation_up": 70,
        "elevation_down": 100
    }, {
        "id": 16,
        "length": 8.4,
        "elevation_up": 120,
        "elevation_down": 130
    }, {
        "id": 17,
        "length": 7,
        "elevation_up": 140,
        "elevation_down": 150
    }, {
        "id": 18,
        "length": 8.6,
        "elevation_up": 100,
        "elevation_down": 120
    }, {
        "id": 19,
        "length": 11,
        "elevation_up": 130,
        "elevation_down": 180
    }, {
        "id": 20,
        "length": 11.7,
        "elevation_up": 170,
        "elevation_down": 150
    }, {
        "id": 21,
        "length": 7.4,
        "elevation_up": 40,
        "elevation_down": 60
    }, {
        "id": 22,
        "length": 8.7,
        "elevation_up": 20,
        "elevation_down": 50
    }, {
        "id": 23,
        "length": 9.3,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 24,
        "length": 9.6,
        "elevation_up": 70,
        "elevation_down": 80
    }, {
        "id": 25,
        "length": 8.7,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 26,
        "length": 10.6,
        "elevation_up": 10,
        "elevation_down": 20
    }, {
        "id": 27,
        "length": 11.2,
        "elevation_up": 20,
        "elevation_down": 10
    }, {
        "id": 28,
        "length": 11.8,
        "elevation_up": 10,
        "elevation_down": 20
    }, {
        "id": 29,
        "length": 10.7,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 30,
        "length": 10.8,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 31,
        "length": 8,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 32,
        "length": 7.2,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 33,
        "length": 7.9,
        "elevation_up": 10,
        "elevation_down": 10
    }, {
        "id": 34,
        "length": 8.4,
        "elevation_up": 20,
        "elevation_down": 20
    }, {
        "id": 35,
        "length": 11.3,
        "elevation_up": 10,
        "elevation_down": 0
    }, {
        "id": 36,
        "length": 8.9,
        "elevation_up": 50,
        "elevation_down": 50
    }
];